### ISSUE TITLE
not working on 1.17

### ISSUE THREAD

**Issue by wb1016** [chirs241097/jline4mcdsrv#10]
1.17 minecraft, 0.11.3 loader, 0.35.1 API, lithium mod is running.
using AdoptOpenJDK 16.
the server starts normally, but only this mod is not working.
works fine on 1.16.5 minecraft.

**Comment by Fourmisain** [comment]
Are you using the right version?
For 1.17 you should use version 0.2.0 which is marked as an alpha release on CurseForge, so either look at "Recent Files" (on the right-hand side) or click on "Files", "View All" to see it.

**Comment by wb1016** [comment]
i dont know why, but it is working now somehow.
