### ISSUE TITLE
[Feature request] Configurable prompt

### ISSUE THREAD

**Issue by cs32767** [chirs241097/jline4mcdsrv#17]
It would be nice to have an option in the config file to change the "prompt" in front of commands (which is currently hardcoded to a slash) to any other character or string.

**Comment by Fourmisain** [comment]
Oh, there was another issue here!
Right, the prompt is not actually part of the command (it's purely visual) and especially when copy-pasting you get two slashes - which willl work but it's unintuitive to look at.
The highlighting is also broken with another slash.

Just made another release adding the config option and fixing the highlighting.
