### ISSUE TITLE
Unable to create a system terminal on Windows

### ISSUE THREAD

**Issue by Snootiful** [chirs241097/jline4mcdsrv#2]
When a server with jline4mcdsrv is started on Windows, the following warning is displayed in the console:
> Oct 17, 2020 5:12:06 PM org.jline.utils.Log logr
> WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)

This causes jline3 to create a dumb terminal, disabling features like auto completion and syntax highlighting. Right now, jline4mcdsrv on Windows only adds highlighting to the server log.

The jline3 repository README states:
> On the Windows platform, relying on native calls is mandatory, so you need to have either Jansi or JNA library in your classpath along with the jline-terminal-jansi or jline-terminal-jna jar. Failing to do so will create a dumb terminal with no advanced capabilities.

Hopefully Jansi or JNA can be added with relative ease to solve this issue.

**Comment by Snootiful** [comment]
I just checked issue #1 again, and I believe that solving this issue with the suggested solution might solve #1 as well.

**Comment by chirs241097** [comment]
Please try the latest version on curseforge.

**Comment by Snootiful** [comment]
Yup, latest version works as expected on Windows.
