### ISSUE TITLE
Add the mod on Modrinth

### ISSUE THREAD

**Issue by AmibeSkyfy16** [chirs241097/jline4mcdsrv#20]
I think it would be great to see this mod on https://modrinth.com

Thank you for this cool project !

**Comment by Fourmisain** [comment]
I'd love to do it!

@chirs241097 If you can invite me or give permission to create a page I can maintain the mod on Modrinth too!

**Comment by chirs241097** [comment]
I hereby grant you the permission to publish this mod on Modrinth.

I do not have an account there. You can publish it under yours.

Thank you for all the efforts you've dedicated to this project to keep it alive over the years.

**Comment by Fourmisain** [comment]
![Good news everyone!](https://media.tenor.com/hyVt5PDLlzcAAAAC/futurama-good-news-everyone.gif)

After what felt like an eternity, [the project has finally been approved by Modrinth!](https://modrinth.com/mod/jline4mcdsrv)
