### ISSUE TITLE
[Feature Requests] Support Mcdreforged

### ISSUE THREAD

**Issue by Redapple-one** [chirs241097/jline4mcdsrv#22]
> Mcdreforged:https://github.com/Fallen-Breath/MCDReforged

This mod doesn't work in my Server
Like this:
![image](https://github.com/chirs241097/jline4mcdsrv/assets/134820858/5d384d20-41ad-47c4-b905-ee81a2718b77)

**Comment by Redapple-one** [comment]
I can't use command history, auto completion and syntax highlighting

**Comment by Fourmisain** [comment]
Hm... I don't believe this can be solved on our end, if it can be solved at all.

MCDReforged runs the Minecraft server in a separate process and directly controls the standard input/output of the server.
However, jline4mcdsrv tries to add JLine and JLine needs a system terminal, which only MCDR has access to.

So the only potential way to make this work is to add JLine to MCDR and somehow communicate the needed information (like command completion) with the Minecraft server/this mod.
It _may_ be possible to write a MCDR plugin that does that, but I really have no idea.

Personally I've never heard of MCDR (or MCD) until now and I don't think I'll ever gonna use it, so I'm not seeing myself writing a plugin for it either.
I can't speak for Chris or anyone else, so I'll leave this issue open for now.

I just wonder...
If you're already modding the server, can't you find mods to replace the MCDR plugins you're using?
