### ISSUE TITLE
[Feature Request] Better Log4j Config compatibility

### ISSUE THREAD

**Issue by unilock** [chirs241097/jline4mcdsrv#25]
I use [Better Log4j Config](https://modrinth.com/mod/better-log4j-config) on my heavily modded server to adjust logging parameters to make issues easier to debug, and to filter out log spam from various mods.

Unfortunately, JLine4MCDSrv seems to completely override / reset the changes Better Log4j Config makes to the Log4j config.

Would it be possible to have some sort of compatibility between the two mods?

**Comment by Fourmisain** [comment]
You don't need a mod for that, you can just start your server with your Log4j configuration like that:
`-Dlog4j.configurationFile=/path/to/your/log4j2.xml`
(and `-Dlog4j2.formatMsgNoLookups=true -Dlog4j.skipJansi=false` while you're at it)
and change the `logPattern` inside `jline4mcdsrv.toml` accordingly.

You can find the log config vanilla uses for 1.21 inside `logging-1.2.7.jar`.
Here's a slightly modified version, matching jline4mcdsrv's default (colors plus shortened logger name):
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
    <Appenders>
        <Console name="SysOut" target="SYSTEM_OUT">
            <PatternLayout pattern="%style{[%d{HH:mm:ss}]}{blue} %highlight{[%t/%level]}{FATAL=red, ERROR=red, WARN=yellow, INFO=green, DEBUG=green, TRACE=blue} %style{(%logger{1})}{cyan} %highlight{%msg{nolookups}%n}{FATAL=red, ERROR=red, WARN=normal, INFO=normal, DEBUG=normal, TRACE=normal}" />
        </Console>
        <RollingRandomAccessFile name="File" fileName="logs/latest.log" filePattern="logs/%d{yyyy-MM-dd}-%i.log.gz">
            <PatternLayout pattern="[%d{HH:mm:ss}] [%t/%level] (%logger): %msg{nolookups}%n" />
            <Policies>
                <TimeBasedTriggeringPolicy />
                <OnStartupTriggeringPolicy />
            </Policies>
        </RollingRandomAccessFile>
    </Appenders>
    <Loggers>
        <Root level="info">
            <filters>
                <MarkerFilter marker="NETWORK_PACKETS" onMatch="DENY" onMismatch="NEUTRAL" />
            </filters>
            <AppenderRef ref="SysOut"/>
            <AppenderRef ref="File"/>
        </Root>
    </Loggers>
</Configuration>
```

Change the `SysOut` and `File` `pattern`s however you like, just make sure `SysOut` is consistent with `jline4mcdsrv.toml`.
If you want to filter certain loggers, you need the full logger name (`%logger`, above config writes it to the log files) and something like this:
```
    <Loggers>
        <!-- deny all logging -->
        <Logger name="FullLoggerName" level="off" additivity="false"></Logger>

        <!-- deny info level logging -->
        <Logger name="AnotherLoggerName">
        	<Filters>
            <LevelRangeFilter minLevel="INFO" maxLevel="INFO" onMatch="DENY" onMismatch="NEUTRAL" />
        	</Filters>
        </Logger>

       <Root ...
```

Issue with compatiblity is that JLine4MCDSrv wants to add colors, and for that it needs to change the log pattern.
Other than that, nothing should really change, filters, appenders etc should all be unaffected, so I'm not sure what you mean by "completely override(n)".

Maybe I can add a way for JLine4MCDSrv to not override the pattern, but copy it from `SysOut` by setting `logPattern` to `""` or something (afaik Toml doesn't support null) for slightly better compatibility, though I'm not sure if it'll really help.

**Comment by unilock** [comment]
> You don't need a mod for that, you can just start your server with your Log4j configuration like that: ...

I'm aware, but it's easier to ship my custom Log4j config with a modpack with the mod.

<details>

<summary>My Log4j config looks like this:</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Source: https://github.com/FabricMC/fabric-loom/blob/d1f35d42218d0710ca640e6f8bef31b7232a9304/src/main/resources/log4j2.fabric.xml -->
<Configuration status="WARN" packages="com.mojang.util">
	<Appenders>
		<!-- System Out -->
		<Console name="SysOut" target="SYSTEM_OUT">
			<!-- Hide garbage -->
			<Filters>
				<RegexFilter regex=".*has a mass of 0.0, not creating a ShipObject.*" onMatch="DENY" onMismatch="NEUTRAL"/>
				<RegexFilter regex=".*Registering id\=\d+ for (LiquidState|SolidStateImpl|VsBlockState).*" onMatch="DENY" onMismatch="NEUTRAL"/>
				<RegexFilter regex=".*solid box \(\d+ \d+ \d+\) &lt; \(\d+ \d+ \d+\) must not intersect negative box.*" onMatch="DENY" onMismatch="NEUTRAL"/>
			</Filters>

			<PatternLayout>
				<LoggerNamePatternSelector defaultPattern="%style{[%d{HH:mm:ss}]}{blue} %highlight{[%t/%level]}{FATAL=red, ERROR=red, WARN=yellow, INFO=green, DEBUG=green, TRACE=blue} %style{(%logger{1})}{cyan} %highlight{%msg%n}{FATAL=red, ERROR=red, WARN=normal, INFO=normal, DEBUG=normal, TRACE=normal}" disableAnsi="${sys:fabric.log.disableAnsi:-true}">
					<!-- Dont show the logger name for minecraft classes -->
					<PatternMatch key="net.minecraft.,com.mojang." pattern="%style{[%d{HH:mm:ss}]}{blue} %highlight{[%t/%level]}{FATAL=red, ERROR=red, WARN=yellow, INFO=green, DEBUG=green, TRACE=blue} %style{(Minecraft)}{cyan} %highlight{%msg{nolookups}%n}{FATAL=red, ERROR=red, WARN=normal, INFO=normal, DEBUG=normal, TRACE=normal}"/>
				</LoggerNamePatternSelector>
			</PatternLayout>
		</Console>

		<!-- Server GUI -->
		<Queue name="ServerGuiConsole" ignoreExceptions="true">
			<!-- Hide garbage -->
			<Filters>
				<RegexFilter regex=".*has a mass of 0.0, not creating a ShipObject.*" onMatch="DENY" onMismatch="NEUTRAL"/>
				<RegexFilter regex=".*Registering id\=\d+ for (LiquidState|SolidStateImpl|VsBlockState).*" onMatch="DENY" onMismatch="NEUTRAL"/>
				<RegexFilter regex=".*solid box \(\d+ \d+ \d+\) &lt; \(\d+ \d+ \d+\) must not intersect negative box.*" onMatch="DENY" onMismatch="NEUTRAL"/>
			</Filters>

			<PatternLayout>
				<LoggerNamePatternSelector defaultPattern="[%d{HH:mm:ss} %level] (%logger{1}) %msg{nolookups}%n">
					<!-- Dont show the logger name for minecraft classes -->
					<PatternMatch key="net.minecraft.,com.mojang." pattern="[%d{HH:mm:ss} %level] %msg{nolookups}%n"/>
				</LoggerNamePatternSelector>
			</PatternLayout>
		</Queue>

		<!-- latest.log -->
		<RollingRandomAccessFile name="LatestFile" fileName="logs/latest.log" filePattern="logs/%d{yyyy-MM-dd}-%i.log.gz">
			<!-- Hide garbage -->
			<Filters>
				<RegexFilter regex=".*has a mass of 0.0, not creating a ShipObject.*" onMatch="DENY" onMismatch="NEUTRAL"/>
				<RegexFilter regex=".*Registering id\=\d+ for (LiquidState|SolidStateImpl|VsBlockState).*" onMatch="DENY" onMismatch="NEUTRAL"/>
				<RegexFilter regex=".*solid box \(\d+ \d+ \d+\) &lt; \(\d+ \d+ \d+\) must not intersect negative box.*" onMatch="DENY" onMismatch="NEUTRAL"/>
			</Filters>

			<PatternLayout>
				<LoggerNamePatternSelector defaultPattern="[%d{HH:mm:ss}] [%t/%level] (%logger{1}) %msg{nolookups}%n">
					<!-- Dont show the logger name for minecraft classes -->
					<PatternMatch key="net.minecraft.,com.mojang." pattern="[%d{HH:mm:ss}] [%t/%level] (Minecraft) %msg{nolookups}%n"/>
				</LoggerNamePatternSelector>
			</PatternLayout>

			<Policies>
				<TimeBasedTriggeringPolicy />
				<OnStartupTriggeringPolicy />
			</Policies>
		</RollingRandomAccessFile>

		<!-- debug.log -->
		<RollingRandomAccessFile name="DebugFile" fileName="logs/debug.log" filePattern="logs/debug-%i.log.gz">
			<!-- Hide garbage -->
			<Filters>
				<RegexFilter regex=".*Handling inbound packet.*" onMatch="DENY" onMismatch="NEUTRAL"/>
				<RegexFilter regex=".*has a mass of 0.0, not creating a ShipObject.*" onMatch="DENY" onMismatch="NEUTRAL"/>
				<RegexFilter regex=".*Registering id\=\d+ for (LiquidState|SolidStateImpl|VsBlockState).*" onMatch="DENY" onMismatch="NEUTRAL"/>
				<RegexFilter regex=".*solid box \(\d+ \d+ \d+\) &lt; \(\d+ \d+ \d+\) must not intersect negative box.*" onMatch="DENY" onMismatch="NEUTRAL"/>
			</Filters>

			<PatternLayout>
				<LoggerNamePatternSelector defaultPattern="[%d{HH:mm:ss}] [%t/%level] (%logger) %msg{nolookups}%n">
					<!-- Shut up -->
					<PatternMatch key="org.eclipse.jgit." pattern=""/>
				</LoggerNamePatternSelector>
			</PatternLayout>

			<!--	Keep 5 files max	-->
			<DefaultRolloverStrategy max="5" fileIndex="min"/>

			<Policies>
				<SizeBasedTriggeringPolicy size="100MB"/>
				<OnStartupTriggeringPolicy />
			</Policies>
		</RollingRandomAccessFile>
	</Appenders>
	<Loggers>
		<Logger level="${sys:fabric.log.level:-info}" name="net.minecraft"/>
		<Root level="all">
			<AppenderRef ref="DebugFile" level="${sys:fabric.log.debug.level:-debug}"/>
			<AppenderRef ref="SysOut" level="${sys:fabric.log.level:-info}"/>
			<AppenderRef ref="LatestFile" level="${sys:fabric.log.level:-info}"/>
			<AppenderRef ref="ServerGuiConsole" level="${sys:fabric.log.level:-info}"/>
		</Root>
	</Loggers>
</Configuration>
```

</details>

Note the `RegexFilter`s.

I guess the problem is that JLine4MCDSrv doesn't use the `SysOut` appender at all? Would it be possible to use a Log4j config file to filter JLine4MCDSrv's appender?

> Maybe I can add a way for JLine4MCDSrv to not override the pattern, but copy it from `SysOut` by setting `logPattern` to `""` or something (afaik Toml doesn't support null) for slightly better compatibility, though I'm not sure if it'll really help.

If it were possible to have JLine4MCDSrv copy all of the configuration from `SysOut` *except* the `logPattern`, that might also be helpful.

**Comment by unilock** [comment]
Is there a way to retain JLine4MCDSrv's command auto-complete feature without having it replace the `SysOut` appender as well? That way, I could replace the logging pattern with a colored one myself, while still retaining JLine4MCDSrv's ability to auto-complete commands.

**Comment by Fourmisain** [comment]
> I guess the problem is that JLine4MCDSrv doesn't use the SysOut appender at all?

Yes, it replaces it with it's [own appender](https://github.com/chirs241097/jline4mcdsrv/blob/master/src/main/java/org/chrisoft/jline4mcdsrv/JLineAppender.java), to actually be able use JLine - now I see what you mean by (some) stuff being overridden.

> Would it be possible to use a Log4j config file to filter JLine4MCDSrv's appender?

I'm not sure if that's possible - and it's probably isn't the way to go.
My understanding of log configs is that they are a blueprints that define how the whole logging structure is to be constructed.
E.g. the appender type `Console` is [an actual class](https://logging.apache.org/log4j/2.x/javadoc/log4j-core/org/apache/logging/log4j/core/appender/ConsoleAppender.html) registered as a plugin, built through a plugin builder in this case.
While jline4mcdsrv's custom `JLineAppender` could be registered as a plugin too and used in the config like `<JLineAppender name="JLine" ...`, it would be constructed way too early, before even the `MinecraftServer` is instanciated (which the appender needs for command completion and syntax highlighting).

> If it were possible to have JLine4MCDSrv copy all of the configuration from SysOut except the logPattern, that might also be helpful.

Yeah, that's what I was thinking too, gonna see if that's doable.

...

And it is! For filters at least.

There's some other stuff, like `ConsoleAppender` specific attributes, the `target` attribute (whether to print to `SYSTEM_OUT` or `SYSTEM_ERR`), and a properties array, which I think represent `<Property>`s _inside_ an appender, all of which sounds pretty esoteric or hard to support, so I'll just copy the filters for now.

Ran into an issue with [StackDeobfuscator](https://modrinth.com/mod/stackdeobf), since it actually [removes all appenders](https://github.com/booky10/StackDeobfuscator/blob/3f33c8fbb8b5b5e56dcf9ec0db7087b55f303339/common/src/main/java/dev/booky/stackdeobf/util/RemappingRewritePolicy.java#L32-L42), but was able to still get and apply the filter.
Unsure if what StackDeobfuscator does has an effect on how the appenders themselves work, but it doesn't appear so...?

> Is there a way to retain JLine4MCDSrv's command auto-complete feature without having it replace the SysOut appender as well?

No, that is the whole reason why it is being replaced. You can't have the SysOut appender write to the console while JLine tries to manage the inputs, it needs full control over everything, hence SysOut has to go.

Just released a [new version](https://modrinth.com/mod/jline4mcdsrv/version/0.6.1) that copies the filters, give it a try!

**Comment by unilock** [comment]
Ah, now I remember the problem I was having with Better Log4j Config alongside JLine4MCDSrv - somehow, the latter becomes configured to display *all* log messages (including debug and trace messages), which makes the log rather difficult to read.

<details>

<summary>Example of the server console when both mods are installed</summary>

```
[15:58:36] [Server thread/DEBUG] (Quilt Loader/Mixin) #lithium:lithium.mixins.json:chunk.entity_class_groups.TypeFilterableListMixin from mod lithium: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_16 supports class version 60)
[15:58:36] [Server thread/TRACE] (Quilt Loader/Mixin) Added class metadata for me/jellysquid/mods/lithium/common/world/chunk/ClassGroupFilterableList to metadata cache
[15:58:36] [Server thread/TRACE] (Quilt Loader/Mixin) Added class metadata for it/unimi/dsi/fastutil/objects/Reference2ReferenceArrayMap to metadata cache
[15:58:36] [Server thread/TRACE] (Quilt Loader/Mixin) Added class metadata for me/jellysquid/mods/lithium/common/entity/EntityClassGroup to metadata cache
[15:58:36] [Server thread/TRACE] (Quilt Loader/Mixin) Added class metadata for it/unimi/dsi/fastutil/objects/ReferenceLinkedOpenHashSet to metadata cache
[15:58:36] [Server thread/TRACE] (Quilt Loader/Mixin) Added class metadata for it/unimi/dsi/fastutil/objects/AbstractReferenceSortedSet to metadata cache
[15:58:36] [Server thread/TRACE] (Quilt Loader/Mixin) Added class metadata for it/unimi/dsi/fastutil/objects/ReferenceSortedSet to metadata cache
[15:58:36] [Server thread/DEBUG] (Quilt Loader/Mixin) Mixing collections.entity_by_type.TypeFilterableListMixin from #lithium:lithium.mixins.json into net.minecraft.class_3509
[15:58:36] [Server thread/DEBUG] (Quilt Loader/Mixin) #lithium:lithium.mixins.json:collections.entity_by_type.TypeFilterableListMixin from mod lithium: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_16 supports class version 60)
[15:58:36] [Server thread/DEBUG] (Quilt Loader/Mixin) Mixing collections.entity_filtering.TypeFilterableListMixin from #lithium:lithium.mixins.json into net.minecraft.class_3509
[15:58:36] [Server thread/DEBUG] (Quilt Loader/Mixin) #lithium:lithium.mixins.json:collections.entity_filtering.TypeFilterableListMixin from mod lithium: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_16 supports class version 60)
[15:58:36] [Server thread/DEBUG] (Quilt Loader/Mixin) Mixing block.hopper.TypeFilterableListMixin from #lithium:lithium.mixins.json into net.minecraft.class_3509
```

</details>

Any idea what the problem could be?

**Comment by Fourmisain** [comment]
Uhh, no idea really. 🤔
I guess I need to look into how Better Log4j Config works exactly and do some testing with it, will do that tomorrow.

And just to make sure, these messages appear _after_ "Starting jline4mcdsrv", right?
Because everything before that should be completely unaffected.

**Comment by Fourmisain** [comment]
It's a configuration issue with the way Better Log4j Config changes the log levels:
```
		<Logger level="${sys:fabric.log.level:-info}" name="net.minecraft"/>
		<Root level="all">
			<AppenderRef ref="DebugFile" level="${sys:fabric.log.debug.level:-debug}"/>
			<AppenderRef ref="SysOut" level="${sys:fabric.log.level:-info}"/>
			<AppenderRef ref="LatestFile" level="${sys:fabric.log.level:-info}"/>
			<AppenderRef ref="ServerGuiConsole" level="${sys:fabric.log.level:-info}"/>
		</Root>
```

Normally (in vanilla) the Root logger has `info` level logging and the `AppenderRef`s don't set a level.
Since jline4mcdsrv adds the JLine appender directly under the root logger, it'll log everything from the root logger, which will be everything with Better Log4j Config.
I changed it copy the level of the SysOut AppenderRef (and the filters too, because of course Log4j allows you to have them there too... 😅)

And everything appears to work now!
[New version is up!](https://modrinth.com/mod/jline4mcdsrv/version/nWFBSxng)

**Comment by unilock** [comment]
It works! Thank you so much!
