### ISSUE TITLE
[Feature request] Line trimming and blank lines

### ISSUE THREAD

**Issue by CodedSakura** [chirs241097/jline4mcdsrv#3]
As someone who uses a terminal on daily basis, I find this mod especially useful, but unfortunately I've run into some inconveniences:

I think that lines should be white-space trimmed before sending to the server, so it doesn't result in an error after auto-completing.
![Screenshot](https://user-images.githubusercontent.com/23125996/99942806-ea96aa00-2d78-11eb-9fb2-a745f8497f10.png)

Also, blank lines should just be ignored; in a regular terminal pressing `return` is a common way to make sure you're in the right window.
Instead of on sending a blank line and it saying `Unknown or incomplete command`, it should just add a new line.

**Comment by chirs241097** [comment]
Pretty nice idea. I'll try to implement it before the releasing the plugin for 1.17. (Due to time constraints, I don't think I'm able to make a release for 1.16.4 for now.)

**Comment by chirs241097** [comment]
#7 is now merged.
